### ISSUE TITLE
Partials / includes?

### ISSUE THREAD

**Issue by bradgreens** [cognitom/gulp-slim#24]
I love slim and want it in my gulp stack, however I'm trying to do things which used to be available in tools like Rails or the Middleman Gem. Specifically things like partials so I can build out templates with shared header & footer includes.

Some of my struggles are documented here http://stackoverflow.com/a/29043553/845717. You'll see I've slapped on `gulp-file-include` to get a basic include system running... but it's not pretty.

Thoughts?

**Comment by cognitom** [comment]
`slim` depends on rails too much. This is a good thing and also a bad thing, I think. That's why we couldn't integrate it easily into the `gulp` workflows.
But I heard that there's some good moves in 3.1, they're going to support external variables. See discussion on #20.

BTW, any PR is welcome :) Thanks.

**Comment by bradgreens** [comment]
Not sure if anyone has seen the [`slm`](https://github.com/slm-lang/slm) project. [`gulp-slm`](https://github.com/simnalamburt/gulp-slm) covered my desires for partials & template logic.

**Comment by cognitom** [comment]
@bradgreens nice! It seems that `slm` has good compatibility. That would make sense, in some cases.

**Comment by bitencode** [comment]
Sorry @cognitom, Slim in no way depends on Rails.  Slim is used in Sinatra, Roda, and plain ruby systems.  Slim-Rails is the gem that integrates Slim with Rails.  There may be issues with getting Slim to work in a JS environment, but it's not because it depends on Rails at all.

**Comment by cognitom** [comment]
@bitencode Thanks for clarification :)
I've just wanted to point out the dependency on Ruby and logics. I believe we should logic-less mode only but not many (especially rails users) think so :(

**Comment by bitencode** [comment]
@cognitom, the latest versions of slim have the include plug-in built-in (though you have to require it in ruby).  The slimrb command line tool has a way to request that ruby libraries be loaded.  If I send you a pull request with an additional option to gulp-slim that I think would support @bradgreens request would you be interested?  It's something I need too.
