### ISSUE TITLE
script src javascript

### ISSUE THREAD

**Issue by glfead** [cognitom/gulp-slim#27]
Hello,

I use gulp-slim to write slim and convert into a .html file in my 'dist'
but i can't place my 
		
		
		<script src="js/app.js"></script>
		
		
at the bottom of my <body> in slim
I only can place my script source in the head and I don't want to do that

Any suggestions?
Thanks

**Comment by cognitom** [comment]
Hi. Could you put your slim file and gulp file here?
Someone can help you, maybe.

**Comment by glfead** [comment]
Hi, thanks for the response

I want this .html file 
		
		<!doctype html>
		<head>
		...
		<link rel="stylesheet" href="....css">
		</head>
		<body>
		...
		<script src="....js" type="test/javascript"></script>
		</body>
		
I make it in slim :

		doctype html
		head
			...
			link rel="stylesheet" href="....css"
			
		body
			...
			script src="....js" type="text
			
			
But it make that :
			
		<!doctype html>
		<head>
		...
		<link rel="stylesheet" href="....css">
		</head>
		<body>
		...
		script src="....js" type="test/javascript"
		</body>
		
I use a basic gulp task (in coffee)
		
		...
		slim = require 'gulp-slim'
		
		gulp.task 'slim', ->
			gulp.src 'html/*.slim'
			.pipe slim
			.pipe gulp.dest 'html/'
			
			
All the file is good except my javascript source, am I forced to put it in the head to use slim?

**Comment by JGantner** [comment]
Thats a weird problem. I was not able to reproduce it. See https://github.com/JGantner/gulp-slim-issue-27 for my attempt.

In my opinion it should work as expected. At least it did work in my example.

**Comment by glfead** [comment]
Hey! you're right
in your case it's work perfectly, i must have an mistake
thanks
