### ISSUE TITLE
UTF-8 issue

### ISSUE THREAD

**Issue by yozzh** [cognitom/gulp-slim#32]
When i try to compile slim template with russian symbols it returns me an error:
```
Encoding::InvalidByteSequenceError: "\xD8" on US-ASCII
```
So i add this option to spawn object in your module function: 
```
program = spawn(cmnd, arg);
```
changed to
```
program = spawn(cmnd, args, {
        env: {
          "LC_CTYPE":"ru_RU.UTF-8"
        }
      });
```

and it will work OK! Can you fix it or help me to avoid this issue?

**Comment by cognitom** [comment]
Pls send us  your PR :)
Thanks!

**Comment by yozzh** [comment]
PR has been created.

**Comment by coobstar** [comment]
Hows the scene on this one?  We are also running into encoding issues

**Comment by yozzh** [comment]
@coobstar I send a pull request about 20 days ago :) if you need the correct solution - i can send you compiled js library to use it in your project. Or you can get it by yourself from my project https://github.com/fishtag/gulpify/blob/master/gulp/scripts/slim.js

**Comment by cognitom** [comment]
Oops, sorry. I'm back. I've merged the PR into the master. Thank you so much, @yozzh!
